python : 
1. Python is open source  high level ,interpreted,object oriented programming language used for ,web development, software development server side web creation,and machine learning application 
2. Easy to learn and execute 
3. It contains many inbuilt library

Application : 
1. Machine learning
2. Artificial Intelligence
3. Web scraping
4. Data science and data analysis
5. GUI(Graphical user interface)

->Python was invented in the late 1980s by Guido van Rossum

->(Object-Oriented Programming) is a programming paradigm based on the concept of objects, which can contain data in the form of fields (attributes or properties) and code in the form of procedures (methods or functions)sm->Python is called an interpreted language because it executes code line by line using an interpreter rather than compiling the entire code into machine language at once before execution. Here are the main reasons Python is classified as an interpreted language:

->Interpreted Languages: Code is executed line-by-line by an interpreter at runtime. Ex; Python
->Compiled Languages: Code is first translated into machine language by a compiler, creating an executable file, which is then run by the computer. Ex : Java

->Python: Easier to learn, best for beginners, scripting, data science, and rapid development. Emphasizes simplicity and readability.

->Java: Suitable for large-scale, high-performance applications, Android development, and enterprise solutions. Emphasizes performance, scalability, and robustness.

->Yes, Python is a case-sensitive language. This means that Python distinguishes between uppercase and lowercase letters in identifiers such as variable names, function names, class names, and keywordsa 

In [1]:
print('Hello world')

Hello world


Comments : this can be used to explain the code this code will not run

1. single line comment #
2. multiline comment """ this is comment """

In [2]:
#this is single line comment
print('This is single line comment')

This is single line comment


In [4]:
'''
this is multiline comment
'''
print('This is multiline comment')

This is multiline comment


Variables: name given to a memory location.
name='Prajwal'

following are the rules for variable 
1. variable must start with letter or underscore character
2. variable can not start with number 
3. variable name can only contain alphanumeric character
4. Reserved words can not used as variable 
5. Variable names are case sensitive 

Type's of Varible
1. Global variable : Variables that are created outside the function 
2. Local variale : variables that are created inside the function

In [6]:
name='Prajwal'
print(name)

Prajwal


In [9]:
# global variable 
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


In [10]:
#local variable
def example_function():
    local_var = 10  # Local variable
    print(local_var)

example_function()

10


In [8]:
# Keywords:
# Reserved words in python which can not be used as variable
import keyword
print(keyword.kwlist) # List all Python Keywords

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


Data type: data types define the type of data that can be stored and manipulated within a program. 
1. ext Type:	str
2. Numeric Types:	int, float, complex
3. Sequence Types:	list, tuple, range
4. Mapping Type:	dict
5. Set Types:	set, frozenset
6. Boolean Type:	bool(true false)
7. Binary Types:	bytes, bytearray, memoryview,bin
8. None Type:	NoneType

In [6]:
# <!-- type casting :
# the conversion of the one type of data to another type of data -->
# int
# float
# complex
# Boolean
a='1'
a=int(1)
print(1)
print(type(a))

1
<class 'int'>


Operators :  operators are used for calculation on variables and values used in matrix operation.
1. Arithmatic operator +,-,*,/,//,%,**
2. Assignment operator =,==,+=,-=
3. comparision operator ==,!=,>,<,<=,>=
4. logical operator and , or , not 
5. Identify operator is ,is not 
6. membership operator in ,not in 
7. Bitwise operator : And ,OR,XOR,NOT 


In [8]:
# Arithmatic operator : +,-,*,/,%,**
x = 10
y = 4

# Addition
add = x + y
print("Addition:", add)  # Output: 14

# Subtraction
subtract = x - y
print("Subtraction:", subtract)  # Output: 6

# Multiplication
multiply = x * y
print("Multiplication:", multiply)  # Output: 40

# Division
divide = x / y
print("Division:", divide)  # Output: 2.5

# Floor Division
floor_divide = x // y
print("Floor Division:", floor_divide)  # Output: 2

# Modulus
modulus = x % y
print("Modulus:", modulus)  # Output: 2

# Exponentiation
exponent = x ** y
print("Exponentiation:", exponent)  # Output: 10000


Addition: 14
Subtraction: 6
Multiplication: 40
Division: 2.5
Floor Division: 2
Modulus: 2
Exponentiation: 10000


In [9]:
# Assignment operator 
x = 5

# Add and assign
x += 3
print("After += 3:", x)  # Output: 8

# Subtract and assign
x -= 2
print("After -= 2:", x)  # Output: 6

# Multiply and assign
x *= 4
print("After *= 4:", x)  # Output: 24

# Divide and assign
x /= 3
print("After /= 3:", x)  # Output: 8.0

# Floor divide and assign
x //= 2
print("After //= 2:", x)  # Output: 4.0

# Modulus and assign
x %= 3
print("After %= 3:", x)  # Output: 1.0

# Exponentiate and assign
x **= 3
print("After **= 3:", x)  # Output: 1.0


After += 3: 8
After -= 2: 6
After *= 4: 24
After /= 3: 8.0
After //= 2: 4.0
After %= 3: 1.0
After **= 3: 1.0


In [10]:
# Comparision Operator
x = 10
y = 20

# Equal to
print(x == y)  # Output: False

# Not equal to
print(x != y)  # Output: True

# Greater than
print(x > y)  # Output: False

# Less than
print(x < y)  # Output: True

# Greater than or equal to
print(x >= y)  # Output: False

# Less than or equal to
print(x <= y)  # Output: True


False
True
False
True
False
True


In [11]:
# Logical operator 
x = 5
y = 10

# Using logical AND
if x > 0 and y > 0:
    print("Both x and y are greater than 0")  # Output: Both x and y are greater than 0

# Using logical OR
if x > 0 or y < 0:
    print("Either x is greater than 0 or y is less than 0")  # Output: Either x is greater than 0 or y is less than 0

# Using logical NOT
if not x == y:
    print("x is not equal to y")  # Output: x is not equal to y


Both x and y are greater than 0
Either x is greater than 0 or y is less than 0
x is not equal to y


In [12]:
# Identify operator
# Different lists with same content
list1 = [1, 2, 3]
list2 = [1, 2, 3]

# Assigning list1 to list3
list3 = list1

# Using identity operators
print(list1 is list2)    # Output: False (different objects)
print(list1 is list3)    # Output: True (same object)
print(list1 is not list2)# Output: True (different objects)


False
True
True


In [13]:
# membership operator 
my_list = ['apple', 'banana', 'cherry']

if 'banana' in my_list:
    print("Found 'banana' in the list")
else:
    print("Did not find 'banana' in the list")


Found 'banana' in the list


In [14]:
# Bitwise operator
# Bitwise AND example
x = 10    # 1010 in binary
y = 7     # 0111 in binary

print(x & y)   # Output: 2 (0010 in binary)

# Bitwise OR example
print(x | y)   # Output: 15 (1111 in binary)

# Bitwise XOR example
print(x ^ y)   # Output: 13 (1101 in binary)

# Bitwise NOT example
x = 10
print(~x)      # Output: -11 (in decimal)

# Bitwise Left Shift example
x = 5
print(x << 1)  # Output: 10 (1010 in binary)

# Bitwise Right Shift example
x = 5
print(x >> 1)  # Output: 2 (10 in binary)


2
15
13
-11
10
2


In [16]:
#converting number to Binary format 
# octal base starts with 8
# HexaDecimal base starts with 16
# Bin base starts with 4
bin(25),bin(8),oct(25)

('0b11001', '0b1000', '0o31')

In [17]:
0b1001 # Binary to normal number 
0b110011010

410

In [19]:
import math
x=math.sqrt(25)
x

5.0

In [22]:
x=(math.floor(3.2)) #floor round-up to low level
y=(math.ceil(3.2)) # ceil round-up to high level
x,y

(3, 4)

In [26]:
print(math.pow(3,2)) # power 
print(math.pi) #pi value # constant value 
print(math.e) # epsole !

9.0
3.141592653589793
2.718281828459045


DATA STRUCTURE in python: In Python, there are several built-in data structures that are commonly used to organize and manipulate data efficiently. Here are some examples of fundamental data structures in Python
1. String
2. Lists
3. tuples
4. Sets
5. Dictionary

Strings:Anything written inside the quotation i.e string 
1. Immutable  
2. ordered with index value 

In [16]:
mystr=' This is String  '
mystr
mystr1='This is another string '
mystr

' This is String  '

In [17]:
#strinf function 
mystr.lower()
mystr.upper()
mystr.replace('Th','th')
mystr.count('s')
mystr.startswith('t')
mystr.endswith('g')
mystr.split()
str=mystr+mystr1 # string concat
print(mystr.isalpha()) # returns True if all the characters in the text are lett
print(mystr.isalnum()) # returns True if a string contains only letters or numb
print(mystr.isdecimal()) # returns True if all the characters are decimals (0-9)
print(mystr.isnumeric()) # returns True if all the characters are numeric 
mystr.strip()
mystr.rstrip("*") # removes all * character ending of the string 
mystr.lstrip('*')# removes all * character starting of the string 

False
False
False
False


' This is String  '

In programming, slicing is a technique used to access a portion of a sequence, such as a list, string, or array. It allows you to extract a subset of elements from the original sequence.

In [18]:
#String slicing : 
str1="This is String "
str1[0:5] # String slicing - Fetch all characters from 0 to 5 index location excl
str1[6:12] # String slicing - Retreive all characters between 6 - 12 index loc ex
str1[-4:] # Retreive last four characters of the string
str1[-6:] # Retreive last six characters of the string
str1[:4] # Retreive first four characters of the string
str1[:6] # Retreive first six characters of the string

'This i'

Array:a group of similar elements or data items of the same type collected at contiguous memory locations.
containers which are able to store more than one item at the same time i.e array 

Array starts with 0

In python different type of array
1. list
2. tuple
3. sets
4. dictionary

Indexing in pyton :Indexing in Python refers to the accessing of individual elements within a data structure (such as lists, tuples, strings, etc.) using their position or index. Python uses zero-based indexing, meaning the index of the first element is 0, the second element is 1, and so on. Indexing allows you to retrieve, modify, or delete specific elements within a sequence or collection.

Mutable : can change r edit 
immutable : can not change r edit 

List : ordered collection of different data type
1. List is an ordered sequence of items 
2. it is mutable 
3. Allows duplicate elements 
4. list=['this','is',1,'list']

In [19]:
list1=[]
print(type(list1))

<class 'list'>


In [20]:
list1=[10,20,30,'Prajwal','20.2']
list1

[10, 20, 30, 'Prajwal', '20.2']

In [62]:
#list indexing 
list1[0]
list1[2]
list1[10]

30

In [2]:
# list slicing
mylist = ['one' , 'two' , 'three' , 'four' , 'five' , 'six' , 'seven' , 'eight']
mylist[0:3] # Return all items from 0th to 3rd index location excluding the item 
mylist[2:5] # List all items from 2nd to 5th index location excluding the item at
mylist[:3] # Return first three items
mylist[:2] # Return first two items
mylist[-3:] # Return last three items
mylist[-2:] # Return last two items
mylist[-1] # Return last item of the list
mylist[:] # Return whole list

['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']

In [5]:
#list function 
mylist
mylist.append('nine') # Add an item to the end of the list 
mylist
mylist.insert(9,'ten') # Add item at index location 9
mylist
mylist.insert(1,'ONE') # Add item at index location 1
mylist
mylist.remove('ONE') # Remove item "ONE"
mylist
mylist.pop() # Remove last item of the list
mylist
# mylist.pop(8) # Remove item at index location 8
mylist
del mylist[7] # Remove item at index location 7
mylist
mylist.count('one')
mylist
mylist.extend([12,23])
mylist
# mylist.clear() # Empty List / Delete all items in the list
# mylist

['one', 'two', 'three', 'four', 'five', 'six', 'seven', 12, 'ten', 23, 12, 23]

In [127]:
list1=['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']
list1.reverse()
list1=[9,5,2,99,12,88,34]
list1.sort()
list1.sort(reverse=True)
list1.count(2)
list1

[99, 88, 34, 12, 9, 5, 2]

In [125]:
list10 =['one', 'two', 'three', 'four', 'one', 'one', 'two', 'three']
list10.count('one')

3

List Comprehensions
List Comprehensions provide an elegant way to create new lists.
It consists of brackets containing an expression followed by a for clause, then zero or more for
or if clauses.


In [132]:
mystring = "WELCOME"
mylist = [ i for i in mystring ] # Iterating through a string Using List Comprehe
mylist
mylist1 = [ i for i in range(40) if i % 2 == 0] # Display all even numbers betwee
mylist1
mylist2 = [ i for i in range(40) if i % 2 == 1] # Display all odd numbers between
mylist2
mylist3 = [num**2 for num in range(10)] # calculate square of all numbers between
mylist3


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Tuples: grouping of similer data elements as same in list excepts tuple are immutable.
1. ordered collection are data items 
2. Immutable 
3. Allows duplicates 
4. tuple=()
5. When we do not want to change the data over time, tuple is a preferred data type.
6. Iterating over the elements of a tuple is faster compared to iterating over a list.

In [133]:
tup1 = () # Empty tuple
tup2 = (10,30,60) # tuple of integers numbers
tup3 = (10.77,30.66,60.89) # tuple of float numbers
tup4 = ('one','two' , "three") # tuple of strings
tup5 = ('Asif', 25 ,(50, 100),(150, 90)) # Nested tuples
tup6 = (100, 'Asif', 17.765) # Tuple of mixed data types
tup7 = ('Asif', 25 ,[50, 100],[150, 90] , {'John' , 'David'} , (99,22,33))
len(tup7) 

6

In [134]:
# Tuple indexing
tup2[0] # Retreive first element of the tuple
tup4[0] # Retreive first element of the tuple
tup4[0][0] # Nested indexing - Access the first character of the first tuple elem
tup4[-1] # Last item of the tuple
tup5[-1] # Last item of the tuple

(150, 90)

In [28]:
# Tuple Slicing 
mytuple = ('one' , 'two' , 'three' , 'four' , 'five' , 'six' , 'seven' , 'eight')
mytuple[0:3] # Return all items from 0th to 3rd index location excluding the item
mytuple[2:5] # List all items from 2nd to 5th index location excluding the item a
mytuple[:3] # Return first three items
mytuple[:2] # Return first two items
mytuple[-3:] # Return last three items

mytuple[-2:] # Return last two items
mytuple[-1] # Return last item of the tuple
mytuple[:] # Return whole tuple
mytuple[0:-1]

('one', 'two', 'three', 'four', 'five', 'six', 'seven')

adding and deleting items tuple not supports

In [136]:
list1=[mytuple]
list1

[('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight')]

In [141]:
# sorting
mytuple2 = (43,67,99,12,6,90,67)
sorted(mytuple2) # Returns a new sorted list and doesn't change original tuple
sorted(mytuple2, reverse=True) # Sort in descending order

[99, 90, 67, 67, 43, 12, 6]

Sets : These are collection similer data items which is 
1. unordered and unidexed collection of items 
2. set elements are unique.
3. Duplicates are not allowed
4. Immutable but set itself is mutable we can add or remove from it 
5. set={ }

In [146]:
myset = {1,2,3,4,5} # Set of numbers
myset
len(myset) #Length of the set
my_set = {1,1,2,2,3,4,5,5}
my_set # Duplicate elements are not allowed.
myset1 = {1.79,2.08,3.99,4.56,5.45} # Set of float numbers
myset1
myset2 = {'Asif' , 'John' , 'Tyrion'} # Set of Strings
myset2
myset3 = {10,20, "Hola", (11, 22, 32)} # Mixed datatypes
myset3
# myset3 = {10,20, "Hola", [11, 22, 32]} # set doesn't allow mutable items like lis
myset3

{(11, 22, 32), 10, 20, 'Hola'}

In [147]:
myset

{1, 2, 3, 4, 5}

In [161]:
myset.add(6) # adding new item
myset
myset.update([5,3,6,8]) # multiple item update but duplicates not allowed
myset
myset.remove(6) # removing items
myset
myset.discard(8) # removing items
myset
myset.clear() # deleting all items
myset

set()

In [162]:
# set operation 
# Union
A = {1,2,3,4,5}
B = {4,5,6,7,8}
C = {8,9,10}
A | B # Union of A and B (All elements from both sets. NO DUPLICATES)
A.union(B) # Union of A and B
A.union(B, C) # Union of A, B and C.

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [165]:
#intersection
A = {1,2,3,4,5}
B = {4,5,6,7,8}

A & B # Intersection of A and B (Common items in both sets)
# A.intersection(B) Intersection of A and B
"""
Updates the set calling the intersection_update() method with the intersection of
For below example Set A will be updated with the intersection of A & B.
"""
A.intersection_update(B)
A

{4, 5}

In [171]:
# Difference
A = {1,2,3,4,5}
B = {4,5,6,7,8}
A - B # set of elements that are only in A but not in B
A.difference(B) # Difference of sets

B- A # set of elements that are only in B but not in A
B.difference(A)
"""
Updates the set calling the difference_update() method with the difference of set
For below example Set B will be updated with the difference of B & A.
"""
B.difference_update(A)
B


{6, 7, 8}

In [172]:
# Symmetric Difference
A = {1,2,3,4,5}
B = {4,5,6,7,8}
A ^ B # Symmetric difference (Set of elements in A and B but not in both. "EXCLUD
A.symmetric_difference(B) # Symmetric difference of sets
"""
Updates the set calling the symmetric_difference_update() method with the symmetr
For below example Set A will be updated with the symmetric difference of A & B.
"""
A.symmetric_difference_update(B)
A


{1, 2, 3, 6, 7, 8}

Dictionary:A python dictionary is a collection of key and value pairs separated by a colon (:) & enclosed in curly braces {}
1. It it mutable data type
2. duplicates are not allowed
3. key must be unique but value can b same 
4. dic={ "Key":"value"}

In [30]:
mydict = dict() # empty dictionary
mydict
mydict = {} # empty dictionary
mydict
mydict = {1:'one' , 2:'two' , 3:'three'} # dictionary with integer keys
mydict
mydict = dict({1:'one' , 2:'two' , 3:'three'}) # Create dictionary using dict()
mydict

{1: 'one', 2: 'two', 3: 'three'}

In [31]:
mydict = {'A':'one' , 'B':'two' , 'C':'three'} # dictionary with character keys
mydict
mydict = {1:'one' , 'A':'two' , 3:'three'} # dictionary with mixed keys
mydict
mydict.keys() # Return Dictionary Keys using keys() method
mydict.values() # Return Dictionary Values using values() method
mydict.items() # Access each key-value pair within a dictionary 
mydict = {1:'one' , 2:'two' , 'A':['asif' , 'john' , 'Maria']} # dictionary with 
mydict
mydict = {1:'one' , 2:'two' , 'A':['asif' , 'john' , 'Maria'], 'B':('Bat' , 'cat')}
mydict

{1: 'one', 2: 'two', 'A': ['asif', 'john', 'Maria'], 'B': ('Bat', 'cat')}

In [32]:
mydict.keys()
mydict.values()
mydict[1]

'one'

In [33]:
# Dictionary function
mydict={'Name':'Prajwal','ID':4524,'DOB':"14-04-2002",'Address':'Banglore'}
mydict
mydict['DOB']=2002
mydict
dict={'Education':'Engg'}
mydict.update(dict)
mydict
mydict['Job']="searching"
mydict
mydict.pop('Job') # removing perticuler item
mydict
mydict.popitem() # last element removed randomly
mydict
del[mydict['Address']] # deleting item 
mydict
mydict.clear() # deleting all items 

USER INPUT : Python allows for user input.
That means we are able to ask the user for input.

In [197]:
name=input("Enter your name")
print(name)

Enter your name this 


this 


Conditional statement:

Python supports the usual logical conditions from mathematics:

1. Equals: a == b
2. Not Equals: a != b
3. Less than: a < b
4. Less than or equal to: a <= b
5. Greater than: a > b
6. Greater than or equal to: a >= b

These conditions can be used in several ways, most commonly in "if statements" and loops.

An "if statement" is written by using the if keyword.

In [196]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


Nested if statements means condition inside the if condition

In [199]:
age=int(input("Enter your age"))
if age <18:
    print('Your not eligible for voting')
elif age<=18:
    print("Your eligible for vote")
else:
    print('You are eligible')

Enter your age 34


You are eligible


Looping statement : a fundamental aspect of programming languages that provide a way to execute a block of code repeatedly. 

For loop: The for loop iterates over a sequence (such as a list or string) or any iterable object. It executes a block of code once for each element in the sequence. 
Iterating over a list

In [3]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x) 

for i in enumerate( 'python'):
    print(i)


apple
banana
cherry
(0, 'p')
(1, 'y')
(2, 't')
(3, 'h')
(4, 'o')
(5, 'n')


while loop : The while loop repeatedly executes a block of statements as long as a specified condition evaluates to True. It is used when you do not know beforehand how many times the loop will need to execute.

1. Break statement : It used to  breaks or exits the loop when conditions gets true.
2. Continue statement :It  Used to skip certain iterations of a loop based on a condition without exiting the loop entirely.
3. Pass statement : In Python, the pass statement is a null operation or a placeholder that does nothing when it executes. It is used when a statement is syntactically required but you have no action to perform or you want to implement something later. The pass statement is typically used as a placeholder for future code or as a temporary placeholder in code development.

In [35]:
# Using break in a for loop : breaks the statement when the  if conditions gets true 
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)
    if fruit == "banana":
        break

apple
banana


In [37]:
# Using continue in a while loop  : continue except the element of if conditions 
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


In [38]:
count = 0
while count < 20:
    count += 1
    if count == 3:
        continue
    if count==10:
        break
    print(count)

1
2
4
5
6
7
8
9


In [23]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


range () function : The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

In [207]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


Function : It is a block of code used to perform specific tasks.A function is a block of code which only runs when it is called.

Information can be passed into functions as arguments

In [39]:
# You can pass data, known as parameters, into a function
def my_function(): # my function is parameter
  print("Hello from a function")

my_function()

Hello from a function


In [8]:
def greet():
    print('Hello')
    print('Good Morning')
greet()


def add(x,y):
    c=x+y
    d=x-y
    return c,d
x1=int(input('Enter the num:'))
y2=int(input('Enter the num: '))
add(x1,y2)

Hello
Good Morning


Enter the num: 3
Enter the num:  4


(7, -1)

In [40]:
# Arguments are specified after the function name, inside the parentheses
def add(p,q):
    print("addition of two number is :",p+q)
x=int(input("Enter 1st number:"))
y=int(input("Enter 2nd number:"))
add(x,y)

Enter 1st number: 2
Enter 2nd number: 3


addition of two number is : 5


In [19]:
def person(name,age):
    print(name)
    print(age)
person('Navin',30)

def person(name,age=10):
    print(name)
    print(age-1)
person('name')

def sum(a,*b):
    c=a
    for i in b:
        c=c+i
    print(c)
sum(5,6,34,78)

Navin
30
name
9
123


In [44]:
def calculate_percentage(obtained_marks, total_marks):
    if total_marks == 0:
        return 0  # To avoid division by zero error
    percentage = (obtained_marks / total_marks) * 100
    return percentage

# Get input from the user
obtained = 100
total = 40

# Calculate the percentage
percentage = calculate_percentage(obtained, total)
percentage
# Print the result
# print(f"The percentage of marks obtained is {percentage:.2f}%")


250.0

In [46]:
# number is even r add 
def even_add(num):
    if num%2==0:
        print('Even')
    else:
        print('odd')
num=int(input("Enter the number "))
even_add(num)

Enter the number  3


odd


Lambda: lambda is an anonymous function without name 
lambda function can have any number of agruments but only one expression.The expression is evaluated and returned 
we use lambda function when we require nameless function for a short period of time 

In [51]:
addition =lambda a:a+10
addition(5)

15

In [50]:
product=lambda a,b: a*b
product(5,10)

50

In [49]:
prt=lambda p,r,t:(p*r*t)/100
prt(10,20,30)

60.0

In [4]:
# Filter function : 
def is_even(n):
    return n%2==0
num=[3,2,4,6,8,9,56,76]
evens=list(filter(lambda n:n%2==0,num))
evens

[2, 4, 6, 8, 56, 76]

In [7]:
# map function
def update(n):
    return n*2

nums=[3,2,3,5,7,8,9]
double=list(map(lambda n:n*2,nums))
double

[6, 4, 6, 10, 14, 16, 18]

Map function : The map() function applies a given function to each item of an iterable (list, tuple etc.) and
returns a list of the results.

function : The function to execute for each item of given iterable.
iterable : It is a iterable which is to be mapped

In [6]:
# map function()
def calculateSquare(n):
    return n*n
    
numbers=(1,2,3,4)
result=map(calculateSquare,numbers)
print(result)
numbersSquare=list(result)
print(numbersSquare)

[1, 4, 9, 16]


In [2]:
numbers=(1,2,3,4) #map with  lambda
result=map(lambda x:x*x,numbers)
print(result)
numbersSquare=list(result)
print(numbersSquare)

[1, 4, 9, 16]


Random Function : gives a random number

In [13]:
import random
a=['Head','Tail',457]
flip=random.choice(a)
flip

457

OOP's: Object-Oriented Programming (OOP) is  a programming paradigm that uses objects and classes in programming.
The key principles of OOP are encapsulation, inheritance, polymorphism, and abstraction.

class :  Class is a "blueprint" for creating objects.class is the main building block and acts like template for the object .
Object : Object is a collection of data function and are also called as instance of class or class variable 
In python everything is treated as an object.

Variable defined inside the class are called class variable and function are called as method

In [ ]:
# OOP's:object oriented programming language
class sample:
    x=10
    y=20
s=sample()
print(s.x)
print(s.y)

In [14]:
class student:
    mark1,mark2,mark3=45,67,72
    def process(self):
        sum=self.mark1+self.mark2+self.mark3
        avg=sum/3
        print("total marks:",sum)
        print("Average marks:",avg)
        return
s=student()
s.process()

total marks: 184
Average marks: 61.333333333333336


Constructor : Constructor is a special method used for initializing newly created objects.It is called automatically when you create a new instance of class.The constructor method in Python is defined using the __init__ method.

In [3]:
class sample:
    def __init__(self,num):
        print('constructor of class')
        self.num=num
        print('The value is ',self.num)
s=sample(10)

constructor of class
The value is  10


Inheritance : Inheritance is a fundamental concept in object-oriented programming that refers to the process of creating new class from existing class.
->Inheritance is a fundamental concept in object-oriented programming that allows a class (called the child or subclass) to inherit attributes and methods from another class (called the parent or superclass). This promotes code reuse and can make programs easier to understand and maintain.

Type's of inheritance : 
1.  Single Inheritance: A class inherits from one parent class.One parent, one child.
2.  Multiple Inheritance: A class inherits from more than one parent class.Multiple parents, one child.
3.  Multilevel Inheritance: A class inherits from another class, which in turn inherits from another class, forming a chain. A chain of inheritance
4.  Hierarchical Inheritance: Multiple classes inherit from a single parent class.One parent, multiple children.
5.  Hybrid Inheritance: A combination of two or more types of inheritance.Combination of multiple inheritance types.

In [5]:
class Parent:
    def func1(self):
        print('This is function is in Parent class')

class Child(Parent):
    def func2(self):
        print('This function is in Child class')
object=Child()
object.func1()
object.func2()

This is function is in Parent class
This function is in Child class


Polymorphism : Polymorphism is a core concept in object-oriented programming that allows methods to be used interchangeably with different types of objects. It means "many forms" and allows objects of different classes to be treated as objects of a common superclass. Polymorphism is typically achieved through method overriding and operator overloading.

->It refers to the ability of different objects to responf to the same method or function called in different ways.It allows object of different classes to be treated as object of a common superclass.

2 type's of Polymorphism : 
1. method overriding :Method overriding allows a subclass to provide a specific implementation of a method already defined in its superclass.
2. method overloading :It allows the same operator to have different meanings based on the context, particularly the types of operands involved.

In [6]:
#Method overriding :
class Animal:
    def sound(self):
        print("This is a generic animal sound")

class Dog(Animal):
    def sound(self):
        print("Woof!")

class Cat(Animal):
    def sound(self):
        print("Meow!")

# Using polymorphism
def make_sound(animal):
    animal.sound()

# Creating instances
dog = Dog()
cat = Cat()

# Calling the same method on different objects
make_sound(dog)  # Output: Woof!
make_sound(cat)  # Output: Meow!


Woof!
Meow!


In [7]:
# Method overloading
class Vector:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return Vector(self.x + other.x, self.y + other.y)

    def __str__(self):
        return f"Vector({self.x}, {self.y})"

# Creating instances
v1 = Vector(2, 3)
v2 = Vector(1, 4)

# Adding two vectors using the overloaded + operator
v3 = v1 + v2

print(v3)  # Output: Vector(3, 7)


Vector(3, 7)


Encapsulation : Encapsulation  is one of the fundamental principles of object-oriented programming (OOP). It refers to the bundling of data (attributes) and methods (functions) that operate on the data into a single unit, typically a class. Encapsulation restricts direct access to some of the object's components, which can prevent the accidental modification of data. This is often achieved by making attributes private and providing public methods to access and modify them.

Benefits of Encapsulation
1. Data Hiding: Internal object details are hidden from the outside world. Only the necessary aspects are exposed.
2. Modularity: The class can be modified without affecting other parts of the program.
3. Maintenance: Easier to maintain and understand the code since the object's data and behaviors are encapsulated.
4. Control: Provides control over how the data is accessed or modified.

PYTHON ARRAY :  Arrays in python can only contain elements of same data types i.e data type should be homogeneous.

TypeCodes Available for the array module for various data types
1. 'i'-integer type-2
2. 'f'-Float type-4
3. 'd'-float type-8
4. 'u'-unicode character-2

In [6]:
import array as arr
vals=arr.array('i',[2,3,4,5])
print(vals)
for i in vals:
    print(i)

vals1=arr.array('u',['P','Y','T','H','O','N'])
for i in vals1:
    print(i)

array('i', [2, 3, 4, 5])
2
3
4
5
P
Y
T
H
O
N


In [11]:
import array as arr

# Creating an array of integers
array = arr.array('i', [1,2, 3, 4, 5])
array1=arr.array('d',[1.2,1.5,1.6])
array2=arr.array('u',['a','b','g'])

# typecode
print(array.typecode)
print(array1.typecode)
print(array2.typecode)

print(array)
print(array1)
print(array2)

# lenght of an array 
print(len(array))
print(len(array1))
print(len(array2))

i
d
u
array('i', [1, 2, 3, 4, 5])
array('d', [1.2, 1.5, 1.6])
array('u', 'abg')
5
3
3


In [13]:
for i in range(0,len(array)):
    print(array[i],end=' ')
print('\n')

for i in range(0,len(array1)):
    print(array1[i],end=' ')
print('/n')

for i in range(0,len(array2)):
    print(array2[i],end=' ')

1 2 3 4 5 

1.2 1.5 1.6 /n
a b g 

In [20]:
from array import array

# Initialize an empty array of integers
arr = array('i', [])

# Input the length of the array
n = int(input('Enter the length of the array: '))

# Input the elements of the array
for i in range(n):
    x = int(input('Enter the next value: '))
    arr.append(x)

# Print the array
print(arr)

# Input the value to search for in the array
val = int(input('Enter the value for search: '))

# Search for the value in the array
k = 0
found = False
for e in arr:
    if e == val:
        print(f'The value {val} is found at index: {k}')
        found = True
        break
    k += 1

# If the value is not found in the loop, print a message
if not found:
    print(f'The value {val} is not found in the array.')


Enter the size of array:  2
Enter the next value: 3
Enter the next value: 4


array('i', [3, 4])


Enter the value for search :  5


The value 5 is not found in the array.


In [14]:
#Accessing elements from an array using index values
x=list(range(1,100,2))
new_array=arr.array('i',x)

# new_array

# printing the array
for i in range(0,len(new_array)):
    print(new_array[i],end=' ')
print('/n')

#accessing the element at index '25'
print(new_array[25])

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 /n
51


In [43]:
# Adding Element in an array
new_arr=arr.array('i',[3,4,5,6,7,8,9])
for i in range(0,len(new_arr)):
    print(new_arr[i],end=' ')
print(end='\n')

# adding elements in the array
new_arr.insert(0,2) # insert is used to add with position 
new_arr.insert(0,1)
# print the new array 
for i in range(0,len(new_arr)):
    print(new_arr[i],end=' ')

print(end='\n')

#using append # append is used to add element end of the array
new_arr.append(10)
for i in range(0,len(new_arr)):
    print(new_arr[i],end=' ')

3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 10 

In [47]:
#Updating element in an array 
new_array=arr.array('i',[1,2,3,4,5])

for i in range(0,len(new_array)):
    print(new_array[i],end=' ')
print('\n')

#updating the array 
new_array[2]=30  # assigned new value at index 2
for i in range(0,len(new_array)):
    print(new_array[i],end=' ')
    

1 2 3 4 5 

1 2 30 4 5 

In [51]:
# deleting element in an array using pop method
new_array=arr.array('i',[1,2,3,4,5])
new_array.pop(4) # deletes element at index position
for i in range(0,len(new_array)):
    print(new_array[i],end=' ')

1 2 3 4 

In [53]:
# deleting element in an array using remove
new_array=arr.array('i',[1,2,3,4,5])
new_array.remove(1) # deletes element at value 
for i in range(0,len(new_array)):
    print(new_array[i],end=' ')

2 3 4 5 

In [84]:
#slicing an array 

# Create an array using a list of numbers from 0 to 99 with a step of 3
x = list(range(0, 100, 3))
arr1 = arr.array('i', x)

# Slicing operation (positive indexing)
arr0 = arr1[10:20]

# Print the sliced array elements
for i in range(len(arr0)):
    print(arr0[i], end=' ')
print()  # for a newline

# Negative indexing example
# Here we will take a negative slice from the original array arr1
# Let's take a slice from index -20 to -10
arr2 = arr1[-20:-10]

for i in range(len(arr2)):
    print(arr2[i], end=' ')
print()  # for a newline

# Reversing the order of the sliced array arr2
arr3 = arr2[::-1]

for i in range(len(arr3)):
    print(arr3[i], end=' ')
print()  # for a newline


30 33 36 39 42 45 48 51 54 57 
42 45 48 51 54 57 60 63 66 69 
69 66 63 60 57 54 51 48 45 42 


In [90]:
# searching operation in an array using index()
x=list(range(0,100000,2))
search_array=arr.array('i',x)

# print first 10 elements of the array
for i in range(0,len(search_array[0:10])):
    print(search_array[i],end=' ')
print('/n')

# search the number 1002 in the array 
index=search_array.index(10002)
res=search_array[index]
print(index,res)

0 2 4 6 8 10 12 14 16 18 /n
5001 10002


In [94]:
# sorting operation
sort_array=arr.array('i',[5,4,3,2,1,4,6,9])
sorted_array=sort_array.tolist()

#asceding order
sorted_array.sort()
print(sorted_array)

# descending order
sorted_array.sort(reverse=True)
print(sorted_array)

[1, 2, 3, 4, 4, 5, 6, 9]
[9, 6, 5, 4, 4, 3, 2, 1]


Array values from user input

Homogeneous : Homogeneous arrays are of same datatype 
Heterogeneous : Heterogeneous arrays are of different datatype.

In [105]:
# numpy array 
# creating numpy array 
import  numpy as np 
arr=np.array([1,2,3,4,5,6])
print(arr)
print()

#creating an array with all zeros
print(np.zeros((2,2)))
print()

# creating an array with alll ones 
print(np.ones((2,2)))
print()

# creating an array with constant value
print(np.full((3,3),10))
print()

# creating an identity matrix 
print(np.eye((4)))
print()

#creating an array with random values
print(np.random.random((2,3)))

[1 2 3 4 5 6]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0.50681963 0.05936333 0.85153352]
 [0.6768793  0.24357819 0.31286798]]


what is the difference between array and list:
1. Array: Arrays in python can only contain elements of same data types i.e data type should be homogeneous
2. Lists: Lists in python can contain elements of different data types i.e data type of lists can be heterogenous.

what is __init__ :
it is a constructor method in python and is automatically called to allocate memory when a new object/instace is created.

Slicing index : slicing is taking part of.[start:stop:step]
-> Default value for start is 0,stop is number of items,step is 1.
->slicing can be done on strings,arraya,lists and tuples
list[0:0]->starts with 0 and ends with 0,
list[0:3]->starts wiht 0 and ends with 3,
list[-1]->last element
list[0:-1]->except last element

what is the use of self in python :
Self is used to represent the instance of the class.with this keyword,you can access the attributes and methods of the class in python.It binds the attributes with the given arguments.self is used in different places and often thought to be a keyword

What are modules and packages in python :
In Python, packages and modules are organizational units used to structure and manage code, making it easier to organize and reuse functionality across different projects. Here's a breakdown of what packages and modules are:

1. Modules : 
Definition: A module in Python is a file containing Python definitions (functions, classes, variables) and statements. It allows you to logically organize your Python code.
Purpose: Modules help in organizing Python code into reusable units. They aid in maintaining clarity, reducing complexity, and improving code reuse across different projects.

2. Packages:
Definition: A package in Python is a way of organizing related modules. It consists of a directory containing multiple module files and a special file named __init__.py which indicates that the directory should be treated as a package.

Purpose: Packages provide a hierarchical structure to the module namespace, making it easier to manage and import modules. They allow for better organization and separation of concerns within large projects.

Key Points:
1. Importing: Modules and packages are imported using the import statement in Python. For example, to import a module my_module from my_package, you use import my_package.my_module.
2. Namespaces: Each module and package has its own namespace, which helps in avoiding naming conflicts and organizing code logically.
3. Reusability: Modules and packages promote code reuse across different projects or within the same project, enhancing maintainability and reducing duplication of code.

1. What is lambda in python ? Why is is used ?:
In Python, an anonymous function, also known as a lambda function, is a small, anonymous (unnamed) function defined with the lambda keyword. Lambda functions are used when you need a simple function for a short period of time, often where defining a full function using def would be overly verbose or unnecessary.

Characteristics of Lambda Functions:
1. Anonymous: Lambda functions do not have a name; they are defined inline where they are used.
2. Single Expression: Lambda functions can only contain a single expression, unlike regular functions which can contain multiple statements.
3. Implicit Return: The result of the expression is automatically returned from the lambda function.

static typing and dynamic typing refer to different approaches in how programming languages handle variable types during program execution:
1. Static Typing: In a statically typed language, variables are explicitly declared with their data types, and type checking is performed at compile-time. Once a variable is declared with a certain type, it cannot change to another type.
Example Languages: Java, C, C++, Swift, Kotlin.
Data type's are checked  before execution
Characteristics:
1. Type Declarations: Variables must be explicitly declared with their types before they can be used.
2. Compile-time Checking: Type checking is done at compile-time, ensuring that type errors are caught before the program runs.
3. Type Safety: Helps catch errors related to incompatible types early in the development process.
4. Performance: Can lead to potentially faster execution due to compile-time optimizations.

// Static typing in Java
int x = 10;   // `x` is declared as an integer
x = "Hello";  // Compilation error: incompatible typ

2. Dynamic Typing: In a dynamically typed language, variables do not have explicit type declarations. The type of a variable is determined implicitly at runtime based on the value assigned to it. Variables can change types during execution.
Example Languages: Python, JavaScript, Ruby, PHP.
Data type's are checked during execution
Characteristics:
1. Implicit Type Declaration: Variables are not explicitly typed; their types are inferred from the context.
2. Runtime Checking: Type checking occurs at runtime, allowing variables to change types dynamically.
3. Flexibility: Offers more flexibility in coding as variables can adapt to different types as needed.
4. Ease of Use: Reduces verbosity and allows for quicker prototyping and development cycles.e
 //Dynamic typing in Python
x = 10        # `x` is inferred as an integer
x = "Hello"   # Now `x` is inferred as a string
s


Python Libraries:

PANDAS :Pandas is a powerful and flexible open-source data analysis and manipulation library for Python. It provides data structures and functions needed to work with structured data seamlessly.
1. Data Alignment: Automatic alignment of data from different sources.
2. Integrated Handling of Missing Data: Functions to detect, remove, or replace missing values.
3. Flexible Data Structures: DataFrames and Series provide flexible structures to manage data.
4. Label-Based Indexing: Access data by labels, making it intuitive to work with.
5. Group By: Split data into groups, apply functions to each group, and combine the results.
6. High Performance: Efficient operations on large datasets.

Pandas is an essential tool for data scientists and analysts. It provides powerful capabilities for data manipulation and analysis, making it easier to work with structured data in Python. For more detailed information and advanced functionalities, you can refer to the Pandas documentation. 

NumPy is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently. Here’s an overview of its key features, array operations, and common functions.

1. N-Dimensional Array Object (ndarray):
A powerful N-dimensional array object which is the core of NumPy.

2. Mathematical Functions:
A wide range of mathematical functions to operate on arrays.

3. Linear Algebra, Fourier Transform, and Random Number Generation:
Functions for linear algebra, Fourier transforms, and random number generation.

4. Integration with Other Libraries:
Integration with other scientific computing libraries like SciPy and Pandas.

NumPy is an essential library for numerical computations in Python. It provides efficient and powerful tools for array manipulation and a wide range of mathematical functions, making it a cornerstone for scientific computing. For more detailed information and advanced functionalities, 

MATPLOTLIB : Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It is widely used for plotting and offers a variety of chart types to help visualize data effectively. Here’s a detailed overview of its key features, plotting types, and common operations.

1. Versatile Plotting: Supports various types of plots including line plots, scatter plots, bar charts, histograms, pie charts, and more.
2. Customization: Extensive options to customize plots such as titles, labels, legends, colors, and styles.
3. Integration: Works well with other libraries like NumPy, Pandas, and SciPy.
4. Interactive Plots: Can create interactive plots using widgets and event handling.
5. Publication Quality: High-quality output suitable for publication.

Matplotlib is a versatile and powerful library for creating a wide range of static, animated, and interactive plots in Python. It is highly customizable and integrates well with other scientific computing libraries. For more detailed information and advanced functionalities, you can refer to the Matplotlib documentation

SEABORN : Seaborn is a Python data visualization library built on top of Matplotlib. It provides a high-level interface for creating attractive and informative statistical graphics. Seaborn integrates well with Pandas data structures and is designed to work with DataFrames, making it particularly useful for data analysis tasks.

1. High-Level Interface: Simplifies the creation of complex visualizations with fewer lines of code compared to Matplotlib.
2. Statistical Plotting: Built-in support for statistical plots such as bar plots, box plots, violin plots, and more.
3. Integration with Pandas: Works seamlessly with Pandas DataFrames, allowing easy plotting of data directly from data structures.
4. Themes and Color Palettes: Provides default themes and color palettes for aesthetically pleasing plots.
5. Automatic Estimation and Plotting: Automatically estimates and plots trends and relationships within the data.

Seaborn is a powerful and user-friendly library for creating attractive and informative statistical plots in Python. It simplifies the process of data visualization and integrates seamlessly with Pandas, making it an excellent choice for data analysis tasks. For more detailed information and advanced functionalities, you can refer to the Seaborn documentation.